-- Base schema expected by src/services/api.ts when Supabase is configured.
-- Apply this in Supabase SQL editor, then insert your device + telemetry data.

create table if not exists public.devices (
  id text primary key,
  name text not null,
  type text not null,
  vendor text not null,
  model text not null,
  ip text not null,
  mac text not null,
  device_category text not null default 'iot' check (device_category in ('iot', 'home')),
  last_seen_at timestamptz not null default now(),
  status text not null default 'good' check (status in ('good', 'suspicious', 'blocked', 'disconnected'))
);

alter table public.devices drop constraint if exists devices_status_check;
alter table public.devices
  add constraint devices_status_check
  check (status in ('good', 'suspicious', 'blocked', 'disconnected'));

create table if not exists public.device_metrics (
  id bigint generated by default as identity primary key,
  device_id text not null references public.devices (id) on delete cascade,
  recorded_at timestamptz not null default now(),
  latency_ms numeric not null default 0,
  packet_loss_pct numeric not null default 0,
  block_events integer not null default 0,
  network_activity_kbps numeric not null default 0
);

alter table public.device_metrics
  add column if not exists network_activity_kbps numeric not null default 0;

create index if not exists device_metrics_device_id_recorded_at_idx
  on public.device_metrics (device_id, recorded_at desc);

create table if not exists public.device_advisories (
  id bigint generated by default as identity primary key,
  device_id text not null references public.devices (id) on delete cascade,
  title text not null,
  source text not null,
  url text not null,
  published_at timestamptz not null,
  category text not null check (category in ('outage', 'security')),
  summary text,
  generated_at timestamptz
);

create index if not exists device_advisories_device_id_published_at_idx
  on public.device_advisories (device_id, published_at desc);

alter table public.devices enable row level security;
alter table public.device_metrics enable row level security;
alter table public.device_advisories enable row level security;

drop policy if exists "Allow read devices" on public.devices;
drop policy if exists "Allow read metrics" on public.device_metrics;
drop policy if exists "Allow read advisories" on public.device_advisories;
drop policy if exists "Allow delete devices" on public.devices;

create policy "Allow read devices"
  on public.devices
  for select
  using (true);

create policy "Allow read metrics"
  on public.device_metrics
  for select
  using (true);

create policy "Allow read advisories"
  on public.device_advisories
  for select
  using (true);

create policy "Allow delete devices"
  on public.devices
  for delete
  using (true);
